### ISSUE TITLE
ETN Address not showing and Payment ID not full length when using wallet-rpc feature

### ISSUE THREAD

**Issue by Unyxos** [electroneum/electroneum-integrations-wordpress-woocommerce-BETA#1]
Hi!

I installed this demo on my test environment and I noticed that when we use the wallet-rpc feature, the ETN address don't display on the checkout's page, and the payment ID is very small (view pic for example) : 

![image](https://user-images.githubusercontent.com/11515332/37516268-d85b673a-290d-11e8-9149-a66812eaf24d.png)

(My wallet-rpc is running fine)

Also, when using the Private View + Address feature, the transaction never show as completed on the checkout's page even with more than 10-20 confirmations (the ETN address and Payment ID both display without any issue)

**Comment by ETN-A** [comment]
Just wondering if with the Private View + Address feature there's been a change in the meantime re: transactions not showing as completed...

**Comment by ksrupan** [comment]
Hi,
Checked in our testing environment order using electroneum payment with Wallet address & View Key settings. Here also faced the same problem of  the transaction never show as completed on the checkout's page. Always showed "We are waiting for your payment to be confirmed" even though the transaction was closed in Electroneum block chain. How to proceed for getting the payment confirmation?

**Comment by ETN-A** [comment]
Well, to make it perhaps more puzzling, we have successfully tested with the PV-Key and address setup (so not with wallet-rpc) and got the "Your transaction has been successfully confirmed" message and also the relevant update on the back-end.

**Comment by gomez2126** [comment]
How long before the gateway is open for use on WooCommerce? I've got a product ready to launch and want to be able to accept ETN. I'm not a developer...simply a merchant interested in accepting ETN ASAP. Thanks so much...
